# Generated by Django 3.2.8 on 2026-06-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_void',
            field=models.BooleanField(default=False),
        ),
    ]
