# Generated by Django 5.2.15 on 2026-06-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_menurole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menurole',
            name='url_name',
        ),
    ]
