# Generated by Django 5.2.15 on 2026-06-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_menurole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menurole',
            old_name='cdelete',
            new_name='delete',
        ),
    ]
