# Generated by Django 5.2.15 on 2026-06-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_cdelete_menurole_delete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuRole',
        ),
    ]
